Import('env')
from os import path
# extract library name from current/parent path
modname = path.basename(path.abspath('..'))
libname = path.basename(path.abspath('.'))
name       = modname+'_'+libname 
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('../..').srcnode())]
components = 	[                    
                ]
# --------------------------------------------------------------------------
publicHeaders = [
'moonray_static_check.h',
'moonray_nonvirt_baseclass.h'
]

env.DWAInstallInclude(publicHeaders, 'moonray/common/mcrt_macros')
()
env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include'),
                                      env.Dir('$INSTALL_DIR/include/moonray')],
                             COMPONENTS=components)
env.Append(CPPPATH=incdir)
