Import('env')

# ---------------------------------------------------------------

target = 'UsdUVTexture.so'
cc_source = ['UsdUVTexture.cc']
ispc_source = ['UsdUVTexture.ispc']
json_source = ['UsdUVTexture.json']
components = [
    'rendering_shading',
    'shading_ispc',
    'shading_eval_ispc',
    'scene_rdl2'
]

# ---------------------------------------------------------------

env.DWAForceWarningAsError()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
