Import('env')

env.Tool('ispc_dso', toolpath = ['../../../bart_tools'])
# ---------------------------------------------------------------

name = 'dso_debugmap'
target = 'DebugMap.so'
cc_source = ['DebugMap.cc']
ispc_source = ['DebugMap.ispc']
json_source = ['DebugMap.json']
components = [
    'render_util',
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2',
    'texturing_sampler',
]

# ---------------------------------------------------------------
# FIXME: Performance Warning: Modulus
# operator with varying types is very inefficient.
env.AppendUnique(ISPCFLAGS = ['--wno-perf'])

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
