Import('env')

# ---------------------------------------------------------------

name = 'dso_cookielightfilter_v2'
target = 'CookieLightFilter_v2.so'
sources = ['CookieLightFilter_v2.cc']
components = [
    'scene_rdl2'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWARdl2Dso(env.File(target), sources)
env.DWAInstallRdl2Dso(dso)
env.DWAComponent(name, COMPONENTS=components)
