Import('env')

env.Tool('ispc_dso', toolpath = ['../../../bart_tools'])

# ---------------------------------------------------------------

name = 'dso_switchmaterial'
target = 'SwitchMaterial.so'
cc_source = ['SwitchMaterial.cc']
ispc_source = ['SwitchMaterial.ispc']
json_source = ['SwitchMaterial.json']
components = [
    'render_util',
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
