Import('env')
from os import path


# extract library name from current/parent path
modName = path.basename(path.abspath('..'))
libName = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name       = modName+'_'+libName
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('../..').srcnode())]

components = [
    'common_mcrt_util',
    'render_util'
]

# --------------------------------------------------------------------------


public_headers = [
            'Timer.h'
]
env.DWAInstallInclude(public_headers, 'moonray/common/time')

env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)

env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include'),
                                      env.Dir('$INSTALL_DIR/include/moonray')],
                             COMPONENTS=components)
env.Append(CPPPATH=incdir)
env.DWALinkValidate(name)
