#! /bin/tcsh -fb
# Copyright 2023-2024 DreamWorks Animation LLC
# SPDX-License-Identifier: Apache-2.0

pdflatex SamplingStrategy.tex
bibtex SamplingStrategy
pdflatex SamplingStrategy.tex
pdflatex SamplingStrategy.tex
