import os
Import('env')

name = 'dso_usdpreviewsurface'
target = 'UsdPreviewSurface.so'
cc_source = ['UsdPreviewSurface.cc']
ispc_source = ['UsdPreviewSurface.ispc']
json_source = ['UsdPreviewSurface.json']
components = [
    'render_util',
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2'
]

# --------------------------------------------------------------
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)

env.DWAInstallIspcDso(dso)

baseDso = env.DWAComponent(
    name,
    COMPONENTS=components
)
env.AlwaysBuild(baseDso)

