Import('env')

# ---------------------------------------------------------------

name = 'dso_rectlight'
target = 'RectLight.so'
sources = ['RectLight.cc']
components = [
    'scene_rdl2'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWARdl2Dso(env.File(target), sources)
env.DWAInstallRdl2Dso(dso)
env.DWAComponent(name, COMPONENTS=components)
