Import('env')

# ---------------------------------------------------------------

target = 'UsdPrimvarReader_point.so'
cc_source = ['UsdPrimvarReader_point.cc']
ispc_source = ['UsdPrimvarReader_point.ispc']
json_source = ['UsdPrimvarReader_point.json']
components = [
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2',
    'map_primvar'
]

# ---------------------------------------------------------------

env.DWAForceWarningAsError()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
