Import('env')
from os import path
# extract library name from current/parent path
modname = path.basename(path.abspath('..'))
libname = path.basename(path.abspath('.'))
# --------------------------------------------------------------------------
name       = modname+'_'+libname
sources    = env.DWAGlob('*.cc')
incdir     = [str(env.Dir('../..').srcnode())]
components = 	[
                ]
# --------------------------------------------------------------------------
env.DWAInstallInclude(env.DWAGlob('*.h'), 'moonray/common/geometry')
()
env.DWAUseComponents(components)
lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=target, CPPPATH=incdir, COMPONENTS=components)
env.DWAInstallSConscriptStub(name, LIBS=target,
                             CPPPATH=[env.Dir('$INSTALL_DIR/include'),
                                      env.Dir('$INSTALL_DIR/include/moonray')],
                             COMPONENTS=components)
env.Append(CPPPATH=incdir)
env.DWALinkValidate(name)
