Import('env')
from os import path

name = 'test_render'
# --------------------------------------------------------------------------

components = [
                'bvh_shading_ispc',
                'pdevunit',
                'render_util',
                'scene_rdl2',
                'shading_eval_ispc',
                'shading_ispc',
                'texturing_sampler',
]
env.DWAUseComponents(components)

sources = [
    'TestRender.cc'
]
ispc_output, header = env.IspcShared(['TestRender.ispc'])
sources += ispc_output

incdir = [str(env.Dir('.').srcnode())]

# --------------------------------------------------------------------------

# TestRender.cc needs a path to TestRender_ispc_stubs.h
env.AppendUnique(CPPPATH = [env.Dir('.')])

lib = env.DWASharedLibrary(name, sources)
target = env.DWAInstallLib(lib)
env.DWAComponent(name, LIBS=[target], CPPPATH=incdir, COMPONENTS=components)
env.DWALinkValidate(name)

