Import('env')

# ---------------------------------------------------------------

name = 'dso_perspectivecamera'
target = 'PerspectiveCamera.so'
sources = ['PerspectiveCamera.cc']
components = [
    'scene_rdl2'
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWARdl2Dso(env.File(target), sources)
env.DWAInstallRdl2Dso(dso)
env.DWAComponent(name, COMPONENTS=components)
