Import('env')

# ---------------------------------------------------------------

name = 'dso_usdtransform2d'
target = 'UsdTransform2d.so'
cc_source = ['UsdTransform2d.cc']
ispc_source = ['UsdTransform2d.ispc']
json_source = ['UsdTransform2d.json']
components = [
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2',
]

# ---------------------------------------------------------------
()
env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
