#include "LightTreeUtil.isph"
#include <scene_rdl2/common/platform/IspcUtil.isph>

// =====================================================================================================================
// References:
// =====================================================================================================================
// [1] Alejandro Conty Estevez and Christopher Kulla. 2018. 
//     "Importance Sampling of Many Lights with Adaptive Tree Splitting"
// =====================================================================================================================
