Import('env')

env.Tool('ispc_dso', toolpath = ['../../../../bart_tools'])
# ---------------------------------------------------------------

name = 'dso_openvdb_map_v2'
target = 'OpenVdbMap_v2.so'
cc_source = ['OpenVdbMap_v2.cc']
ispc_source = ['OpenVdbMap_v2.ispc']
json_source = ['OpenVdbMap_v2.json']
components = [
    'rendering_shading',
    'shading_ispc',
    'scene_rdl2',
]

# ---------------------------------------------------------------

env.DWAUseComponents(components)
dso = env.DWAIspcDso(env.File(target), cc_source, ispc_source, json_source)
env.DWAInstallIspcDso(dso)
env.DWAComponent(name, COMPONENTS=components)
