// Copyright 2023-2024 DreamWorks Animation LLC
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <moonray/rendering/pbr/SamplingDefinitions.h> // generated by the build system

// Progressive Poisson-disk sampling
#if defined(LIB_RENDERING_PBR_SAMPLING_USE_PPD)
#define USE_PPD_PIXEL
#define USE_PPD_LENS
#define USE_BC_TIME             // TODO: 1D progressive Poisson-disk sampling
#define USE_BC_INTEGRATOR_1D    // TODO: 1D progressive Poisson-disk sampling
#define USE_PPD_INTEGRATOR_2D
#endif

#if defined(LIB_RENDERING_PBR_SAMPLING_USE_BC)
#define USE_STRATIFIED_BEST_CANDIDATE
#define USE_BC_LENS
#define USE_BC_TIME
#define USE_BC_INTEGRATOR_1D
#define USE_BC_INTEGRATOR_2D
#endif

#if defined(LIB_RENDERING_PBR_SAMPLING_USE_PMJ02)
#define USE_PMJ02_PIXEL
#define USE_PPD_LENS
#define USE_BC_TIME
#define USE_BC_INTEGRATOR_1D
#define USE_PPD_INTEGRATOR_2D
#endif

#if defined(LIB_RENDERING_PBR_SAMPLING_USE_RANDOM)
#define USE_RANDOM_PIXEL
#define USE_RANDOM_LENS
#define USE_RANDOM_TIME
#define USE_RANDOM_1D
#define USE_RANDOM_2D
#endif

#if defined(USE_POISSON_PIXEL)             \
 || defined(USE_PPD_PIXEL)                 \
 || defined(USE_GENERAL_BEST_CANDIDATE)    \
 || defined(USE_STRATIFIED_BEST_CANDIDATE) \
 || defined(USE_PMJ02_PIXEL)
#define USE_PARTITIONED_PIXEL_2D
#endif

#if defined(USE_LHS_5D)                    \
 || defined(USE_LHS_PD_5D)
#define USE_PARTITIONED_PIXEL_5D
#define USE_PARTITIONED_PIXEL_FOR_LENS
#define USE_PARTITIONED_PIXEL_FOR_TIME
#endif

#if defined(USE_PARTITIONED_PIXEL_2D) || defined(USE_PARTITIONED_PIXEL_5D)
#define USE_PARTITIONED_PIXEL
#endif

#if defined(USE_BC_LENS)                   \
 || defined(USE_PD_LENS)                   \
 || defined(USE_PPD_LENS)
#define USE_PARTITIONED_LENS
#endif

#if defined(USE_BC_TIME)                   \
 || defined(USE_PD_TIME)
#define USE_PARTITIONED_TIME
#endif

#if defined(USE_BC_INTEGRATOR_1D)          \
 || defined(USE_PD_INTEGRATOR_1D)
#define USE_PARTITIONED_1D
#endif

#if defined(USE_BC_INTEGRATOR_2D)          \
 || defined(USE_PD_INTEGRATOR_2D)          \
 || defined(USE_PPD_INTEGRATOR_2D)
#define USE_PARTITIONED_2D
#endif

