Import('env')

# ---------------------------------------------------------------

name = 'dso_rdlcurvegeometry'
target = 'RdlCurveGeometry.so'
sources = ['RdlCurveGeometry.cc']
components = [
    'render_util',
    'rendering_geom',
    'scene_rdl2',
]

# ---------------------------------------------------------------

()
env.DWAUseComponents(components)
dso = env.DWARdl2Dso(env.File(target), sources)
env.DWAInstallRdl2Dso(dso)
env.DWAComponent(name, COMPONENTS=components)
